sudo: required
services:
  - docker

before_install:
  - cd 4.ci_cd_multi_container
  - docker build -t dennistimmers/client_test -f ./services/client/Dockerfile.dev ./services/client

script:
  - docker run dennistimmers/client_test python test/unit_test.py

after_success:
  - ./sh/push_images.sh