sudo: required
services:
  - docker

before_install:
  - cd 4.ci_cd_multi_container
  - docker build -t dennistimmers/client_test -f ./services/client/Dockerfile.dev ./services/client

script:
  - docker run dennistimmers/client_test python test/unit_test.py

after_success:
  - bash sh/push_images.sh

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env-1'
  bucket_name: 'elasticbeanstalk-eu-west-1-419908496760'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_ID
  secret_access_key:
    secure: $AWS_SECRET_KEY