version: '3'

services:

  redis:
    restart: always
    image: "redis:6.0-rc-buster"

  postgres:
    restart: always
    image: 'postgres:12.1'

  api:
    build:
      dockerfile: Dockerfile.dev
      context: services/api
    command: ["flask", "run", "--host", "0.0.0.0"]
    environment:
      - FLASK_APP=app_api.py
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - redis
      - postgres

  client:
    build:
      dockerfile: Dockerfile.dev
      context: services/client
    command: ["flask", "run", "--host", "0.0.0.0"]
    volumes:
      - ./services/client:/usr/app/
    environment:
      - API_HOST=nginx
      - API_PORT=80
      - FLASK_ENV=development
      - FLASK_APP=app_client.py

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: services/nginx
    ports:
      - '5050:80'

  worker:
    build:
      context: ./services/worker
    command: ["python", "-u", "worker.py"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
