version: '3'

services:
  web:
    restart: always
    build:
      context: ./services/web
    volumes:
      - ./services/web:/usr/app/services/web
    command: gunicorn --bind 0.0.0.0:5000 services.web.index:app
    expose:
      - 5000
    environment:
      - FLASK_APP=services/index.py

  nginx:
    restart: always
    build:
      context: ./services/nginx
    ports:
      - 8080:80
    depends_on:
      - web

  test:
    build:
      context: ./services/web
    volumes:
      - ./:/usr/app
    command: ['python', 'services/web/test/unit_test.py']
