# need pg_info binary
FROM python:3.7-slim-buster

WORKDIR /usr/app

# install python dependencies
COPY ./requirements.txt ./
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# copy over the flask api definition
COPY ./ ./

# create volume for fast development
VOLUME ./services/api ./usr/app/

# start Flask server for development
ENV FLASK_ENV "development"
ENV FLASK_APP "app_api.py"
CMD ["flask", "run", "--host", "0.0.0.0"]